#!/usr/bin/env bash
# Deploy an OpenKBS Lambda function with:
#   - functions/_shared/ copied into functions/<name>/_shared/
#   - .env.local rendered into functions/<name>/_env.mjs (side-effect import)
#
# OpenKBS has no custom-env mechanism yet, so we bundle secrets into the zip.
# The _shared/ + _env.mjs copies are gitignored; the canonical sources live in
# ./functions/_shared/ and ./.env.local at repo root.
set -euo pipefail

fn="${1:-}"
if [[ -z "$fn" ]]; then
  echo "usage: scripts/deploy-fn.sh <name>" >&2
  exit 2
fi

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
fn_dir="$repo_root/functions/$fn"
shared_src="$repo_root/functions/_shared"
env_file="$repo_root/.env.local"
config_file="$repo_root/config.json"
career_file="$repo_root/assets/career.json"

if [[ ! -d "$fn_dir" ]]; then
  echo "no such function: $fn_dir" >&2
  exit 1
fi
if [[ ! -f "$env_file" ]]; then
  echo "missing .env.local at repo root" >&2
  exit 1
fi
if [[ ! -f "$config_file" ]]; then
  echo "missing config.json at repo root" >&2
  exit 1
fi
if [[ ! -f "$career_file" ]]; then
  echo "missing assets/career.json at repo root" >&2
  exit 1
fi

cleanup() {
  rm -rf "$fn_dir/_shared" "$fn_dir/_env.mjs"
}
trap cleanup EXIT

# 1. Copy _shared/ into the function dir (with config.json + career.json bundled alongside)
rm -rf "$fn_dir/_shared"
cp -r "$shared_src" "$fn_dir/_shared"
cp "$config_file" "$fn_dir/_shared/config.json"
cp "$career_file" "$fn_dir/_shared/career.json"

# 2. Render .env.local into _env.mjs (each KEY=VALUE becomes process.env.KEY = 'VALUE')
{
  echo "// AUTO-GENERATED by scripts/deploy-fn.sh from .env.local — do not commit."
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    # single-quote-escape the value
    val_escaped="${val//\'/\\\'}"
    echo "process.env.${key} = process.env.${key} || '${val_escaped}';"
  done < "$env_file"
} > "$fn_dir/_env.mjs"

# 3. Deploy
cd "$repo_root"
openkbs fn deploy "$fn"
